echo 4 0 | gmx rms -s qty_cis_solu.gro -f qty_trans_solu.xtc -n qty_solu.ndx -tu ns -o qty_trans_rmsd_solu.xvg
echo 4 13 | gmx rms -s qty_cis_solu.gro -f qty_trans_solu.xtc -n qty_solu.ndx -tu ns -o qty_trans_rmsd_ret.xvg
echo 4 14 | gmx rms -s qty_cis_solu.gro -f qty_trans_solu.xtc -n qty_solu.ndx -tu ns -o qty_trans_rmsd_pocket.xvg
echo 4 15 | gmx rms -s qty_cis_solu.gro -f qty_trans_solu.xtc -n qty_solu.ndx -tu ns -o qty_trans_rmsd_tm6.xvg
echo 4 16 | gmx rms -s qty_cis_solu.gro -f qty_trans_solu.xtc -n qty_solu.ndx -tu ns -o qty_trans_rmsd_296.xvg
echo 4 17 | gmx rms -s qty_cis_solu.gro -f qty_trans_solu.xtc -n qty_solu.ndx -tu ns -o qty_trans_rmsd_265.xvg
echo 4 18 | gmx rms -s qty_cis_solu.gro -f qty_trans_solu.xtc -n qty_solu.ndx -tu ns -o qty_trans_rmsd_113.xvg
echo 4 19 | gmx rms -s qty_cis_solu.gro -f qty_trans_solu.xtc -n qty_solu.ndx -tu ns -o qty_trans_rmsd_181.xvg
echo 4 20 | gmx rms -s qty_cis_solu.gro -f qty_trans_solu.xtc -n qty_solu.ndx -tu ns -o qty_trans_rmsd_268.xvg
echo 4 21 | gmx rms -s qty_cis_solu.gro -f qty_trans_solu.xtc -n qty_solu.ndx -tu ns -o qty_trans_rmsd_207.xvg
echo 4 22 | gmx rms -s qty_cis_solu.gro -f qty_trans_solu.xtc -n qty_solu.ndx -tu ns -o qty_trans_rmsd_186.xvg
echo 4 23 | gmx rms -s qty_cis_solu.gro -f qty_trans_solu.xtc -n qty_solu.ndx -tu ns -o qty_trans_rmsd_191.xvg
echo 4 24 | gmx rms -s qty_cis_solu.gro -f qty_trans_solu.xtc -n qty_solu.ndx -tu ns -o qty_trans_rmsd_187.xvg
echo 4 25 | gmx rms -s qty_cis_solu.gro -f qty_trans_solu.xtc -n qty_solu.ndx -tu ns -o qty_trans_rmsd_188.xvg
echo 4 26 | gmx rms -s qty_cis_solu.gro -f qty_trans_solu.xtc -n qty_solu.ndx -tu ns -o qty_trans_rmsd_189.xvg
echo 4 27 | gmx rms -s qty_cis_solu.gro -f qty_trans_solu.xtc -n qty_solu.ndx -tu ns -o qty_trans_rmsd_117.xvg
echo 4 28 | gmx rms -s qty_cis_solu.gro -f qty_trans_solu.xtc -n qty_solu.ndx -tu ns -o qty_trans_rmsd_292.xvg
echo 4 29 | gmx rms -s qty_cis_solu.gro -f qty_trans_solu.xtc -n qty_solu.ndx -tu ns -o qty_trans_rmsd_212.xvg
echo 4 30 | gmx rms -s qty_cis_solu.gro -f qty_trans_solu.xtc -n qty_solu.ndx -tu ns -o qty_trans_rmsd_295.xvg
echo 4 31 | gmx rms -s qty_cis_solu.gro -f qty_trans_solu.xtc -n qty_solu.ndx -tu ns -o qty_trans_rmsd_208.xvg